version: '2'
services:
    jhispterpostgre-app:
        image: jhispterpostgre
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhispterpostgre-postgresql:5432/jhispterPostgre
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhispterpostgre-postgresql:
        extends:
            file: postgresql.yml
            service: jhispterpostgre-postgresql
